<a href="https://colab.research.google.com/github/jonathanunirodriguez-cyber/Parte-practica-parcial-II/blob/main/BONUS_2_ESTADISTICA_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Manejo de modulos integrados

Numpy: se usa principalmente para trabajar con datos numericos de forma rapida, eficiente y estruvturada. Un objeto de tipo numpy es una arreglo base para hacer matematicas y manipular datos en Python.

Pandas: se usa para trabajar con datos estructurados(como tablas de excel o base de datos). Un objeto tipo panda es cargar, limpiar, transformar  y analizar datos. La usamos para bases de datos relacionados.

In [168]:
import numpy as np
import pandas as pd

#NUMPY

#Como crear algunos arreglos simples con codigo Numpy:

Arreglo matricial en donde todos los elementos son "0":

In [169]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Arreglo matricial en donde todos los elementos son "1":

In [170]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Arreglo de una matriz identidad de tamaño cuadrado:

In [171]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

El siguiente codigo usa entradas (a,b,c) y crea un arreglo que va desde a hasta b (sin tomar este ultimo) pero saltando c espacios entre cada componente del arreglo:

In [172]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

Si queremos un arreglo que en el cual todos sus elementos sean equidistantes entre si en un intervalo pre-establecido usamos las entradas(a, b, c) donde a y b definen el intervalo y c la cantidad de elementos:

In [173]:
np.linspace(0, 15, 7 )

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. ])

Genera 10 valores aleatorios de una distrivucion uniforme en el intervalo (0,1) y los monta en una lista:

In [174]:
np.random.rand(10)

array([0.57909182, 0.06066949, 0.76492981, 0.83811041, 0.95679929,
       0.87314143, 0.45957289, 0.51071227, 0.04352414, 0.73767848])

Genera un valor entero entre los valores dados quitando el segundo valor:

In [175]:
np.random.randint(0, 10)

8

Genera la cantidad pedida de valores aleatorios de una distribucion normal con media 0 y desviacion estandar 1:

In [176]:
np.random.randn(8)

array([ 0.0088418 ,  0.64965509, -1.21560179,  1.26559921,  0.55415861,
       -1.84222682,  0.31775982, -0.65562631])

#Propiedades para el analisis de arreglos usando Numpys:

Contruyendo una lista (lista), dos arreglos matriciales (arrM1) y (arrM2) y un arreglo vectorial (arrV):

In [177]:
lista = [20,5,4]
arrM1 = np.array([[5,11, 9],
                  [0, 7, 5],
                  [13, -3, 8]])
arrM2 = np.array([[1,-4, 6],
                  [5, 2, -3],
                   [8, 1, 4]])
arrV = np.array([11,24,33,30, 23, 24, 37, 27, 25])

Si queremos duplicar una lista la cantidad de elementos de la lista y repetir dos veces cada componente de la lista original en una nueva lista:

In [178]:
lista * 2

[20, 5, 4, 20, 5, 4]

Si queremos multiplicar por algun valor todos los elementos de un arreglo podemos usar cualquiera de los siguientes:

In [179]:
arrM1 * 2

array([[10, 22, 18],
       [ 0, 14, 10],
       [26, -6, 16]])

In [180]:
[x*3 for x in arrM2]

[array([  3, -12,  18]), array([15,  6, -9]), array([24,  3, 12])]

Si queremos saber cuantos componentes y cuantos elementos por componente tiene nuestro arreglo:

In [181]:
arrM2.shape

(3, 3)

Si queremos saber la dimension de nuestro arreglo:

In [182]:
arrM1.ndim

2

Si queremos saber el tipo de componentes que tenemos en nuestro arreglo:

In [183]:
arrV.dtype

dtype('int64')

Si queremos saber la cantidad de elementos que tenemos en todo el arreglo:

In [184]:
arrM1.size

9

Para saber la primera componenete del arreglo:

In [185]:
arrM2[0]

array([ 1, -4,  6])

para saber la ultima componente del arreglo:

In [186]:
arrM1[-1]

array([13, -3,  8])

Para conocer todas las componentes en el intervalo sin tomar la componente de la pocision del final del intervalo:

In [187]:
arrM1[0:2]

array([[ 5, 11,  9],
       [ 0,  7,  5]])

en el siguiente codigo deducimos que las entradas [a,b] da el elemento en esas coordenadas, [:,b] da todos los elementos que esten en la pocisicion "b" en cada arregloda  y [a,:] da la componente "a" del arreglo. Teniendo en cuenta que las pociciones empiezan desde el 0.

In [188]:
print(arrM2[0,2], arrM2[:,2], arrM2[2,:])

6 [ 6 -3  4] [8 1 4]

Suma dos arreglos:

In [189]:
arrM1 + arrM2

array([[ 6,  7, 15],
       [ 5,  9,  2],
       [21, -2, 12]])

Multiplicando el arreglo componenete a componente:

In [190]:
arrM1 * arrM2

array([[  5, -44,  54],
       [  0,  14, -15],
       [104,  -3,  32]])

Multiplicacion matricial:

In [191]:
np.dot(arrM1,arrM2)

array([[132,  11,  33],
       [ 75,  19,  -1],
       [ 62, -50, 119]])

Calcula media, mediana, desviacion estandar, suma de todos los valores, elmento minimo y maximo:

In [192]:
print( np.mean(arrV), np.median(arrV), np.std(arrV), np.sum(arrV), np.min(arrV), np.max(arrV))

26.0 25.0 6.912147117775907 234 11 37

#Manipulacion de arreglos:

Comvertir un arreglo tipo vector en una matriz:

In [193]:
arrV.reshape(3,3)

array([[11, 24, 33],
       [30, 23, 24],
       [37, 27, 25]])

Unir arreglos:

In [194]:
np.concatenate([arrM1, arrM2])

array([[ 5, 11,  9],
       [ 0,  7,  5],
       [13, -3,  8],
       [ 1, -4,  6],
       [ 5,  2, -3],
       [ 8,  1,  4]])

Convertir un arreglo matricial en un tipo vector:

In [195]:
np.concatenate(arrM2.reshape(3,3))

array([ 1, -4,  6,  5,  2, -3,  8,  1,  4])

In [196]:
arrM2.flatten()

array([ 1, -4,  6,  5,  2, -3,  8,  1,  4])

Calcular la inversa de la matriz de un arreglo:

In [197]:
np.linalg.inv(arrM1)

array([[ 0.28286853, -0.45816733, -0.03187251],
       [ 0.25896414, -0.30677291, -0.09960159],
       [-0.3625498 ,  0.62948207,  0.13944223]])

Calcular la transpuesta de la matriz de un arreglo:

In [198]:
np.linalg.matrix_transpose(arrM2)

array([[ 1,  5,  8],
       [-4,  2,  1],
       [ 6, -3,  4]])

#filtrado y condicion

Encontrar valores que cumplan una condicion:

In [199]:
arrV[arrV>20]

array([24, 33, 30, 23, 24, 37, 27, 25])

In [200]:
arrV[(arrV>20) & (arrV < 30)]

array([24, 23, 24, 27, 25])

Encuentra los valores dado la condicion y los remplaza segun queramos

In [201]:
# para este caso los valores que cumplan la condicion se remplazan con 1 y los queno con 0
np.where(arrV>30, 1, 0)

array([0, 0, 1, 0, 0, 0, 1, 0, 0])

In [202]:
np.where(arrV>25, 0, arrV)

array([11, 24,  0,  0, 23, 24,  0,  0, 25])

#Pandas

#Analisis de tablas a travez de pandas:

Creamos la tabla:
creando la data.frames
pandas transforma un objeto tipo diccionario en data.frames

In [203]:
restaurantes = pd.DataFrame({
    "Nombre": [ "Sabor Andino", "Pizza House", "La Parrilla", "Sushi World","Taco Feliz", "Burger City", "Café Central", "Mar Azul",
               "Pasta Mia", "El Rancho", "Green Bowl", "Arepa Mix","Wok Express", "Donde Juan", "Food Planet", "La Terraza",
                "Chicken Hot", "Dulce Vida", "El Fogón", "Urban Food" ],
    "Ciudad": ["Bogotá", "Medellín", "Cali", "Bogotá", "Barranquilla", "Cali", "Bogotá", "Cartagena", "Medellín", "Cúcuta",
               "Bogotá", "Bucaramanga", "Cali", "Bogotá", "Medellín", "Pereira", "Bogotá", "Cali", "Tunja", "Bogotá"],
    "Tipo_Comida": ["Colombiana", "Italiana", "Carnes", "Japonesa", "Mexicana", "Rápida", "Café", "Mariscos", "Italiana", "Carnes",
                    "Vegetariana", "Colombiana", "China", "Típica", "Internacional", "Fusión", "Pollo", "Postres","Tradicional", "Rápida"],
    "Calificacion": [4.5, 4.0, 3.8, 4.7, 4.3, 3.9, 4.3, 4.6, 4.1, 3.7, 4.8, 4.2, 4.0, 3.5, 4.0, 4.4, 3.9, 4.9, 3.6, 4.1 ],
    "Numero_Empleados": [ 15, 10, np.nan, 12, 8, 18, None, 14, np.nan, 22, 9, 7, 11, 13, 25, 16, 19, 5, 17, np.nan],
    "Ventas_Mensuales": [ np.nan, 18000000, 32000000, 27000000, 15000000, 35000000, 12000000, np.nan, 21000000, 29000000,17000000,
                         14000000, 23000000, 26000000,40000000, 31000000, 28000000, 9000000, np.nan, 36000000],
    "Años_Funcionamiento": [12, 5, 20, 7, 3, 10, 15, 8, 6, 25, 4, 11, 40, 18, 9, 14, 13, 2, 30, 5],
    "Entrega_Domicilio": [ "Sí", "Sí", "No", "Sí", None, "Sí", "No", "No", "Sí", "No", "Sí", np.nan, "Sí", "No","Sí", "Sí", np.nan, "No",
        "No", "Sí"]
})

restaurantes

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,Sabor Andino,Bogotá,Colombiana,4.5,15.0,NaN,12,Sí
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
2,La Parrilla,Cali,Carnes,3.8,NaN,32000000.0,20,No
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
4,Taco Feliz,Barranquilla,Mexicana,4.3,8.0,15000000.0,3,None
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
6,Café Central,Bogotá,Café,4.3,NaN,12000000.0,15,No
7,Mar Azul,Cartagena,Mariscos,4.6,14.0,NaN,8,No
8,Pasta Mia,Medellín,Italiana,4.1,NaN,21000000.0,6,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
11,Arepa Mix,Bucaramanga,Colombiana,4.2,7.0,14000000.0,11,NaN
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
16,Chicken Hot,Bogotá,Pollo,3.9,19.0,28000000.0,13,NaN
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No
18,El Fogón,Tunja,Tradicional,3.6,17.0,NaN,30,No
19,Urban Food,Bogotá,Rápida,4.1,NaN,36000000.0,5,Sí

Generar el promedio de alguna variable:

In [204]:
Calificacion_promedio = restaurantes["Calificacion"].mean()
print(f"la Calificacion promedio es: {Calificacion_promedio}")

la Calificacion promedio es: 4.165

si la tabla es demasiado grande y queremos ver algunas filas usamos:

In [205]:
restaurantes.head(2) #primeras dos filas

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,Sabor Andino,Bogotá,Colombiana,4.5,15.0,NaN,12,Sí
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí

In [206]:
restaurantes.tail(2) #ultimas 2 filas

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
18,El Fogón,Tunja,Tradicional,3.6,17.0,NaN,30,No
19,Urban Food,Bogotá,Rápida,4.1,NaN,36000000.0,5,Sí

Tipos de datos, resumen de la base o data.frame:

In [207]:
restaurantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Nombre               20 non-null     object
 1   Ciudad               20 non-null     object
 2   Tipo_Comida          20 non-null     object
 3   Calificacion         20 non-null     float64
 4   Numero_Empleados     16 non-null     float64
 5   Ventas_Mensuales     17 non-null     float64
 6   Años_Funcionamiento  20 non-null     int64
 7   Entrega_Domicilio    17 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.4+ KB

Estadisticas descritivas basicas para variables cuantitativas: \ \
count = cantidad de datos \ \
mean = media aritmetica \ \
std = desviacion años \ \
min = minimo \ \
max = maxiomo

In [208]:
restaurantes.describe()

       Calificacion  Numero_Empleados  Ventas_Mensuales  Años_Funcionamiento
count     20.000000         16.000000      1.700000e+01            20.000000
mean       4.165000         13.812500      2.429412e+07            12.850000
std        0.395068          5.540382      9.122532e+06             9.761768
min        3.500000          5.000000      9.000000e+06             2.000000
25%        3.900000          9.750000      1.700000e+07             5.750000
50%        4.100000         13.500000      2.600000e+07            10.500000
75%        4.425000         17.250000      3.100000e+07            15.750000
max        4.900000         25.000000      4.000000e+07            40.000000

Si queremos conocer la cantidad de filas y columnas:

In [209]:
restaurantes.shape #(filas, columnas)

(20, 8)

Seleccion de columnas utilizando una lista con los respectivos nombres:

In [210]:
restaurantes[["Nombre", "Años_Funcionamiento"]]

          Nombre  Años_Funcionamiento
0   Sabor Andino                   12
1    Pizza House                    5
2    La Parrilla                   20
3    Sushi World                    7
4     Taco Feliz                    3
5    Burger City                   10
6   Café Central                   15
7       Mar Azul                    8
8      Pasta Mia                    6
9      El Rancho                   25
10    Green Bowl                    4
11     Arepa Mix                   11
12   Wok Express                   40
13    Donde Juan                   18
14   Food Planet                    9
15    La Terraza                   14
16   Chicken Hot                   13
17    Dulce Vida                    2
18      El Fogón                   30
19    Urban Food                    5

Si queremos escojer datos que cumplan ciertas condiciones que queramos:

In [211]:
restaurantes[(restaurantes["Años_Funcionamiento"] > 10) & (restaurantes["Años_Funcionamiento"] < 28)]

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,Sabor Andino,Bogotá,Colombiana,4.5,15.0,NaN,12,Sí
2,La Parrilla,Cali,Carnes,3.8,NaN,32000000.0,20,No
6,Café Central,Bogotá,Café,4.3,NaN,12000000.0,15,No
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
11,Arepa Mix,Bucaramanga,Colombiana,4.2,7.0,14000000.0,11,NaN
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
16,Chicken Hot,Bogotá,Pollo,3.9,19.0,28000000.0,13,NaN

In [212]:
restaurantes.isnull() # valores faltantes

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
0,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False
7,False,False,False,False,False,True,False,False
8,False,False,False,False,True,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,True
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,True,False,False
19,False,False,False,False,True,False,False,False

In [213]:
restaurantes.isnull().sum() #suma los valores por columnas, 1 si es faltante 0 si no

Nombre                 0
Ciudad                 0
Tipo_Comida            0
Calificacion           0
Numero_Empleados       4
Ventas_Mensuales       3
Años_Funcionamiento    0
Entrega_Domicilio      3
dtype: int64

In [214]:
restaurantes1= restaurantes.dropna() #elimina las filas con valores faltantes
restaurantes1

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [215]:
restaurantes1.dropna(subset = ["Ventas_Mensuales"]) # se eliminan las filas que tengan valores faltantes solo en la columna nombrada

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [216]:
restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna(restaurantes1["Ventas_Mensuales"].mean())
restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna("desconocido")
restaurantes1 # resmplazar valores por nuestro valor sugerido

/tmp/ipykernel_23259/972295408.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna(restaurantes1["Ventas_Mensuales"].mean())
/tmp/ipykernel_23259/972295408.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Ventas_Mensuales"] = restaurantes["Ventas_Mensuales"].fillna("desconocido")

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Carnes,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [217]:
restaurantes1["Tipo_Comida"] = restaurantes1["Tipo_Comida"].replace("Carnes", "Rápida")
restaurantes1 # remplazar valores por otros

/tmp/ipykernel_23259/2745324989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Tipo_Comida"] = restaurantes1["Tipo_Comida"].replace("Carnes", "Rápida")

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí
9,El Rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No

In [218]:
restaurantes2 = restaurantes1["Ciudad"].drop_duplicates()
restaurantes2

1     Medellín
3       Bogotá
5         Cali
9       Cúcuta
15     Pereira
Name: Ciudad, dtype: object

In [221]:
restaurantes1["Ventas_anuales"] = restaurantes1["Ventas_Mensuales"] * 12
#aplicar funcion
restaurantes1["Años_Funcionamiento_ doble"] = restaurantes1["Años_Funcionamiento"].apply(lambda x: x * 2)
restaurantes1

/tmp/ipykernel_23259/763644032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Ventas_anuales"] = restaurantes1["Ventas_Mensuales"] * 12
/tmp/ipykernel_23259/763644032.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurantes1["Años_Funcionamiento_ doble"] = restaurantes1["Años_Funcionamiento"].apply(lambda x: x * 2)

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Años_Funcionamiento,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
9,El Rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4

In [227]:
restaurantes3 = restaurantes1.rename(columns = {"Años_Funcionamiento" : "Antiguedad"})
restaurantes3

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Antiguedad,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
1,Pizza House,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,Sushi World,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
5,Burger City,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
9,El Rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
10,Green Bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
12,Wok Express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80
13,Donde Juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
14,Food Planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
15,La Terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
17,Dulce Vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4

In [229]:
restaurantes3["Nombre"] = restaurantes3["Nombre"].str.lower()
restaurantes3["Nombre"] = restaurantes3["Nombre"].str.strip()
restaurantes3["Nombre"] = restaurantes3["Nombre"].str.replace("pizza house", "PIZZA house")
restaurantes3

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Antiguedad,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
1,PIZZA house,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,sushi world,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
5,burger city,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
9,el rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
10,green bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
12,wok express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80
13,donde juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
14,food planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
15,la terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
17,dulce vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4

In [233]:
grupo = restaurantes3.groupby("Ciudad")["Ventas_Mensuales"].mean()
grupo

Ciudad
Bogotá      23333333.333333
Cali        22333333.333333
Cúcuta           29000000.0
Medellín         29000000.0
Pereira          31000000.0
Name: Ventas_Mensuales, dtype: object

In [236]:
ordenado = restaurantes3.sort_values(by = "Antiguedad")
ordenado

,Nombre,Ciudad,Tipo_Comida,Calificacion,Numero_Empleados,Ventas_Mensuales,Antiguedad,Entrega_Domicilio,Ventas_anuales,Años_Funcionamiento_ doble
17,dulce vida,Cali,Postres,4.9,5.0,9000000.0,2,No,108000000.0,4
10,green bowl,Bogotá,Vegetariana,4.8,9.0,17000000.0,4,Sí,204000000.0,8
1,PIZZA house,Medellín,Italiana,4.0,10.0,18000000.0,5,Sí,216000000.0,10
3,sushi world,Bogotá,Japonesa,4.7,12.0,27000000.0,7,Sí,324000000.0,14
14,food planet,Medellín,Internacional,4.0,25.0,40000000.0,9,Sí,480000000.0,18
5,burger city,Cali,Rápida,3.9,18.0,35000000.0,10,Sí,420000000.0,20
15,la terraza,Pereira,Fusión,4.4,16.0,31000000.0,14,Sí,372000000.0,28
13,donde juan,Bogotá,Típica,3.5,13.0,26000000.0,18,No,312000000.0,36
9,el rancho,Cúcuta,Rápida,3.7,22.0,29000000.0,25,No,348000000.0,50
12,wok express,Cali,China,4.0,11.0,23000000.0,40,Sí,276000000.0,80

In [239]:
valores = restaurantes3.values # cambiar de pandas a un array
valores

array([['PIZZA house', 'Medellín', 'Italiana', 4.0, 10.0, 18000000.0, 5,
        'Sí', 216000000.0, 10],
       ['sushi world', 'Bogotá', 'Japonesa', 4.7, 12.0, 27000000.0, 7,
        'Sí', 324000000.0, 14],
       ['burger city', 'Cali', 'Rápida', 3.9, 18.0, 35000000.0, 10, 'Sí',
        420000000.0, 20],
       ['el rancho', 'Cúcuta', 'Rápida', 3.7, 22.0, 29000000.0, 25, 'No',
        348000000.0, 50],
       ['green bowl', 'Bogotá', 'Vegetariana', 4.8, 9.0, 17000000.0, 4,
        'Sí', 204000000.0, 8],
       ['wok express', 'Cali', 'China', 4.0, 11.0, 23000000.0, 40, 'Sí',
        276000000.0, 80],
       ['donde juan', 'Bogotá', 'Típica', 3.5, 13.0, 26000000.0, 18,
        'No', 312000000.0, 36],
       ['food planet', 'Medellín', 'Internacional', 4.0, 25.0,
        40000000.0, 9, 'Sí', 480000000.0, 18],
       ['la terraza', 'Pereira', 'Fusión', 4.4, 16.0, 31000000.0, 14,
        'Sí', 372000000.0, 28],
       ['dulce vida', 'Cali', 'Postres', 4.9, 5.0, 9000000.0, 2, 'No',
        108000000.0, 4]], dtype=object)

#Uso en Ciencia de Datos: Ventajas y Desventajas de NumPy y Pandas
Tanto NumPy como Pandas constituyen la columna vertebral del ecosistema de la Ciencia de Datos y el Machine Learning en Python. Sin estas librerías, la implementación de algoritmos de optimización, predicción y análisis estadístico sería inviable debido a las limitaciones de rendimiento y memoria de las estructuras nativas de Python (como las listas).

NumPy (Numerical Python)
Uso en Ciencia de Datos:
Es la librería fundamental para el cómputo científico y el álgebra lineal. En la Ciencia de Datos, casi cualquier algoritmo (desde una regresión lineal hasta una red neuronal profunda) traduce los datos de entrada a arreglos multidimensionales (matrices o tensores). NumPy proporciona la estructura y las funciones matemáticas necesarias para realizar operaciones masivas sobre estos tensores (como el producto punto, inversiones de matrices y cálculo de gradientes) a velocidades extremadamente altas.

implementación de algoritmos:

Ventajas

Velocidad y Rendimiento (C-Engine): Sus bloques internos están escritos en C. Las operaciones se ejecutan a nivel de código compilado, evitando la lentitud del tipado dinámico de Python.

Vectorización: Permite aplicar operaciones matemáticas a todo un bloque de datos simultáneamente sin necesidad de usar bucles for. Esto optimiza drásticamente el tiempo de ejecución del algoritmo.

Eficiencia en Memoria: Almacena los datos en ubicaciones contiguas de la memoria física y exige un tipo de dato fijo, reduciendo drásticamente el consumo de recursos de cómputo.

Desventajas:

Homogeneidad estricta: Un arreglo de NumPy solo puede contener un único tipo de dato (por ejemplo, exclusivamente float64). No permite mezclar de forma eficiente texto con variables numéricas.

Ausencia de etiquetas: Los datos se indexan únicamente por su posición numérica. No cuenta con nombres de columnas ni de filas, lo que dificulta el manejo y la comprensión de bases de datos tabulares complejas.

Pandas (Panel Data)
Uso en Ciencia de Datos:
Se especializa en la manipulación, estructuración y Análisis Exploratorio de Datos (EDA). Es la herramienta clave en la fase de preprocesamiento de un proyecto de Ciencia de Datos. Antes de entrenar un algoritmo, los datos crudos suelen venir con ruidos o imperfecciones; Pandas permite cargar bases de datos relacionales, limpiar registros, filtrar filas bajo condiciones lógicas, agrupar variables y solucionar el problema de los datos faltantes (NaN).

implementación de algoritmos:

Ventajas  

Flexibilidad (Heterogeneidad): Un DataFrame permite alinear en una sola estructura tabular columnas de texto, números enteros, decimales y booleanos, simulando el comportamiento de una base de datos SQL o una hoja de cálculo.

Etiquetado intuitivo: Facilita el acceso, la manipulación y el filtrado de la información mediante nombres explícitos de variables (columnas) e índices, haciendo el código más legible y menos propenso a errores humanos.

Herramientas avanzadas de alineación y limpieza: Cuenta con funciones nativas sumamente potentes para fusionar tablas (merge), agrupar categorías (groupby) y tratar series temporales o datos nulos de manera inmediata.

Desventajas:

Alto consumo de memoria: Pandas genera copias en memoria para muchas de sus transformaciones y arrastra demasiados metadatos (índices, nombres). No está diseñado para trabajar con Big Data (volúmenes de datos que superen la memoria RAM del equipo).

Menor velocidad en cálculo puro: Para evaluar ecuaciones matemáticas complejas o iteraciones algorítmicas, Pandas es notablemente más lento que NumPy debido a su sobrecarga estructural. Por ello, la regla general en Ciencia de Datos es usar Pandas para limpiar el dataset y, justo antes de ingresar el algoritmo, convertirlo a un arreglo numérico puro usando .to_numpy().